var annotated_dup =
[
    [ "Accessory", "d4/de8/classAccessory.html", "d4/de8/classAccessory" ],
    [ "Armor", "d5/df0/classArmor.html", "d5/df0/classArmor" ],
    [ "BoxInfo", "d8/d74/structBoxInfo.html", "d8/d74/structBoxInfo" ],
    [ "Card", "d3/d66/classCard.html", "d3/d66/classCard" ],
    [ "CharacterCard", "d9/df5/classCharacterCard.html", "d9/df5/classCharacterCard" ],
    [ "CollectTask", "d8/d7f/classCollectTask.html", "d8/d7f/classCollectTask" ],
    [ "EnvironmentCard", "de/d97/classEnvironmentCard.html", "de/d97/classEnvironmentCard" ],
    [ "Equipment", "d1/d42/classEquipment.html", "d1/d42/classEquipment" ],
    [ "Game", "d9/d68/classGame.html", "d9/d68/classGame" ],
    [ "GameMap", "d6/d95/classGameMap.html", "d6/d95/classGameMap" ],
    [ "GatheringQuest", "d4/d7b/classGatheringQuest.html", "d4/d7b/classGatheringQuest" ],
    [ "HuntingQuest", "d6/d12/classHuntingQuest.html", "d6/d12/classHuntingQuest" ],
    [ "Input", "d5/d5b/classInput.html", "d5/d5b/classInput" ],
    [ "Item", "d0/dae/classItem.html", "d0/dae/classItem" ],
    [ "KillTask", "d4/dd9/classKillTask.html", "d4/dd9/classKillTask" ],
    [ "MonsterBox", "db/ddc/classMonsterBox.html", "db/ddc/classMonsterBox" ],
    [ "MonsterCard", "dc/df9/classMonsterCard.html", "dc/df9/classMonsterCard" ],
    [ "NPCCard", "d6/da1/classNPCCard.html", "d6/da1/classNPCCard" ],
    [ "Player", "d2/d4b/classPlayer.html", "d2/d4b/classPlayer" ],
    [ "PlayerCard", "d5/d49/classPlayerCard.html", "d5/d49/classPlayerCard" ],
    [ "Quest", "d1/d4f/classQuest.html", "d1/d4f/classQuest" ],
    [ "Renderer", "d1/d52/classRenderer.html", "d1/d52/classRenderer" ],
    [ "Task", "d6/d9c/classTask.html", "d6/d9c/classTask" ],
    [ "TerminalManager", "d0/d23/classTerminalManager.html", "d0/d23/classTerminalManager" ],
    [ "TreeManager", "d6/d82/classTreeManager.html", "d6/d82/classTreeManager" ],
    [ "Viewport", "da/d87/classViewport.html", "da/d87/classViewport" ],
    [ "Weapon", "dc/de5/classWeapon.html", "dc/de5/classWeapon" ]
];